workflows:
  android-debug:
    name: Build StudyMate Debug APK
    max_build_duration: 60

    environment:
      groups:
        - google_credentials

    scripts:
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk