workflows:
  android-apk:
    name: Build StudyMate APK
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
      vars:
        GRADLE_TASK: "assembleDebug"
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          ./gradlew $GRADLE_TASK
    artifacts:
      - app/build/outputs/apk/**/*.apk